### ISSUE TITLE
Daemon crashing on recieving first player joined from CS2-Server

### ISSUE THREAD

**Issue by gnoffer** [startersclan/hlstatsx-community-edition#50]
as discussed [here](https://github.com/startersclan/source-udp-forwarder/issues/47)  daemon is crashing when the first real user joins CS2 Server. 

```
2024-02-01 20:02:01: 192.168.222.183:27015 - PROXY: L 02/01/2024 - 21:02:01.253 - "X<0><[U:Y]><>" entered the game
Can't call method "set" on unblessed reference at .//HLstats_EventHandlers.plib line 564.
```

i used 
`image: startersclan/hlstatsx-community-edition:1.11.2-daemon`

with "restart: unless-stopped" setted within docker-compose file - container restarts automatically and all other real player will be counted correctly, but not the first one as long as the container is running.

**Comment by gnoffer** [comment]
it seesm that the daemon didnt crash, but also did not count it:

`PROXY: L 02/02/2024 - 11:03:03.025 - "A<0><[U:1:B]><>" connected, address "x.x.x.x:61609"`
`020: OK Rcon from "172.18.0.3": "say HLstatsX:CE disabled! Need at least 2 active players (0/2)"`

**Comment by leojonathanoh** [comment]
hmm. Probably need a few days to refresh myself with the code and think of a proper solution. 🤷

**Comment by gnoffer** [comment]
thanks, ive just tested it with two player.
both are counted, but message is still:
`E020: OK Rcon from "172.18.0.3": "say HLstatsX:CE disabled! Need at least 2 active players (1/2)"`

as a hotfix seems to be ok. thanks a lot for your help.

**Comment by leojonathanoh** [comment]
was thinking about the solution. try the latest fix, it should work correctly 😄

**Comment by gnoffer** [comment]
looks good on first single test, can provide more info on thursday when we have our weekly and if there is some more issue.
thanks a lot!
